### ISSUE TITLE
Plugin Modifies Entity Without Any User Interaction

### ISSUE THREAD

**Issue by ziadeh** [amicaldo/strapi-google-maps#6]
### Description
There appears to be a bug within the plugin where opening an entity automatically triggers modifications to the entity and the Save button is activated and a confirmation message is displayed upon exit, even without any user interaction or changes made to the entity.

### Expected Behavior
The entity should not be modified unless there are explicit changes made by the user to the fields or marker.

**Comment by Pijuli** [comment]
Same behaviour here. 
Strapi: 4.24.3

**Comment by brandonperfetti** [comment]
Same behavior here.
Strapi: 5.13.0

**Comment by roodekk** [comment]
This is fixed in Version 2.0.2 using Strapi 5.

**Comment by brandonperfetti** [comment]
Thanks @roodekk - we've upgraded to version 2.0.2, however we're still seeing the same behavior.

I'm noticing that the latest version is still 2.0.1 - could that be the trouble?
https://github.com/amicaldo/strapi-google-maps/releases
